In [18]:
import pandas as pd
import seaborn as sns
from sqlalchemy import engine  
from pandasql import sqldf
from IPython.display import Image

##funcion lambda que hace escribir sql mucho mas facil!
pysqldf = lambda q: sqldf(q, globals())

<style>
.stylish-text {
    font-family: Arial, sans-serif;
    font-size: 36px;
    font-weight: bold;
    color: #ffffff;
    background: linear-gradient(135deg, #ff4b2b, #ff416c);
    padding: 10px 20px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    text-align: center;
    margin: 20px auto;
    width: max-content;
}
</style>

<div class="stylish-text">importamos csv</div>

In [19]:
### Importamos dataset de jugadores de futbol 
jugadores = pd.read_csv("fulbo_data/players.csv")
clubes = pd.read_csv("fulbo_data/clubs.csv")
valuaciones=pd.read_csv("fulbo_data/player_valuations.csv")

In [20]:
jugadores

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.000,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.000,30000000.000
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.000,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.000,8000000.000
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.000,34500000.000
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.000,24500000.000
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.000,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.000,3000000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30516,1214946,Sid Ahmed,Aissaoui,Sid Ahmed Aissaoui,2023,2410,sid-ahmed-aissaoui,Algeria,Blida,Algeria,...,right,183.000,2026-06-30 00:00:00,Aniss Benchabane,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/sid-ahmed-aiss...,RU1,PFK CSKA Moskva,100000.000,150000.000
30517,1225269,Erdem,Çalık,Erdem Çalık,2023,3209,erdem-calik,Türkiye,Istanbul,Türkiye,...,right,NaN,2026-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/erdem-calik/pr...,TR1,Pendikspor,50000.000,50000.000
30518,1229924,Adama,Sidibeh,Adama Sidibeh,2023,2578,adama-sidibeh,NaN,NaN,The Gambia,...,NaN,NaN,2026-05-31 00:00:00,Willie McKay,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/adama-sidibeh/...,SC1,Saint Johnstone Football Club,250000.000,250000.000
30519,1240467,Artem,Prysyazhnyuk,Artem Prysyazhnyuk,2023,6992,artem-prysyazhnyuk,Ukraine,Odesa,Ukraine,...,left,180.000,2025-05-31 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/artem-prysyazh...,UKR1,ZAO FK Chornomorets Odessa,50000.000,50000.000
30520,1240762,Araphat,Mohammed,Araphat Mohammed,2023,2778,araphat-mohammed,NaN,NaN,Ghana,...,left,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/araphat-mohamm...,DK1,Fodbold Club Nordsjælland,50000.000,50000.000

In [21]:
clubes

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,31,26.800,11,35.500,1,Merck-Stadion am Böllenfalltor,17810,€-1.48m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,NaN,27,28.200,15,55.600,6,Yekaterinburg Arena,23000,€-895k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,39,26.000,17,43.600,14,Tüpraş Stadyumu,42445,€-26.00m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,26,27.100,18,69.200,16,Olimpico di Roma,73261,+€63.20m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,30,25.500,22,73.300,21,Tottenham Hotspur Stadium,62850,€-151.40m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,68608,cf-os-belenenses,CF Os Belenenses,PO1,NaN,30,25.700,5,16.700,0,Estádio do Restelo,19980,+-0,NaN,2017,../data/raw/transfermarkt-scraper/2017/clubs.j...,https://www.transfermarkt.co.uk/cf-os-belenens...
422,724,fc-volendam,Football Club Volendam,NL1,NaN,32,22.300,17,53.100,3,Kras Stadion,7384,+€2.30m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/fc-volendam/st...
423,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,NaN,25,26.800,17,68.000,17,Gewiss Stadium,21747,+€74.49m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/atalanta-berga...
424,979,moreirense-fc,Moreirense Futebol Clube,PO1,NaN,29,25.800,17,58.600,3,Estádio C. J. de Almeida Freitas,6153,€-2.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/moreirense-fc/...
425,984,west-bromwich-albion,West Bromwich Albion,GB1,NaN,25,27.800,8,32.000,4,The Hawthorns,26850,€-1.35m,NaN,2020,../data/raw/transfermarkt-scraper/2020/clubs.j...,https://www.transfermarkt.co.uk/west-bromwich-...

In [22]:
valuaciones

,player_id,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,3057,BE1
1,342216,2001-07-20,100000,1241,SC1
2,3132,2003-12-09,400000,126,TR1
3,6893,2003-12-15,900000,984,GB1
4,10,2004-10-04,7000000,398,IT1
...,...,...,...,...,...
473661,1059440,2024-06-10,200000,5724,DK1
473662,1070642,2024-06-10,400000,1177,DK1
473663,1110406,2024-06-10,12000000,2778,DK1
473664,1135770,2024-06-10,25000,173,DK1
473665,1240762,2024-06-10,50000,2778,DK1

<style>
.stylish-text {
    font-family: Arial, sans-serif;
    font-size: 36px;
    font-weight: bold;
    color: #ffffff;
    background: linear-gradient(135deg, #ff4b2b, #ff416c);
    padding: 10px 20px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    text-align: center;
    margin: 20px auto;
    width: max-content;
}
</style>

<div class="stylish-text">SQL EN PYTHON</div>

<style>
.stylish-text {
    font-family: Arial, sans-serif;
    font-size: 16px;
    font-weight: bold;
    color: #ffffff;
    background: linear-gradient(135deg, #ff4b2b, #ff416c);
    padding: 10px 20px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(1, 0, 0, 0.2);
    text-align: center;
    margin: 20px auto;
    width: max-content;
}
</style>

<div class="stylish-text">CONSULTAS BASICAS</div>

+***SELECT FROM***

In [23]:
q="""

SELECT * FROM jugadores


"""

pysqldf(q)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.000,None,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.000,30000000.000
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.000,None,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.000,8000000.000
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,None,NaN,None,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.000,34500000.000
3,77,None,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,None,NaN,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.000,24500000.000
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.000,None,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.000,3000000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30516,1214946,Sid Ahmed,Aissaoui,Sid Ahmed Aissaoui,2023,2410,sid-ahmed-aissaoui,Algeria,Blida,Algeria,...,right,183.000,2026-06-30 00:00:00,Aniss Benchabane,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/sid-ahmed-aiss...,RU1,PFK CSKA Moskva,100000.000,150000.000
30517,1225269,Erdem,Çalık,Erdem Çalık,2023,3209,erdem-calik,Türkiye,Istanbul,Türkiye,...,right,NaN,2026-06-30 00:00:00,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/erdem-calik/pr...,TR1,Pendikspor,50000.000,50000.000
30518,1229924,Adama,Sidibeh,Adama Sidibeh,2023,2578,adama-sidibeh,None,None,The Gambia,...,None,NaN,2026-05-31 00:00:00,Willie McKay,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/adama-sidibeh/...,SC1,Saint Johnstone Football Club,250000.000,250000.000
30519,1240467,Artem,Prysyazhnyuk,Artem Prysyazhnyuk,2023,6992,artem-prysyazhnyuk,Ukraine,Odesa,Ukraine,...,left,180.000,2025-05-31 00:00:00,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/artem-prysyazh...,UKR1,ZAO FK Chornomorets Odessa,50000.000,50000.000
30520,1240762,Araphat,Mohammed,Araphat Mohammed,2023,2778,araphat-mohammed,None,None,Ghana,...,left,NaN,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/araphat-mohamm...,DK1,Fodbold Club Nordsjælland,50000.000,50000.000

<style>
.stylish-text {
    font-family: Arial, sans-serif;
    font-size: 16px;
    font-weight: bold;
    color: #ffffff;
    background: linear-gradient(135deg, #ff4b2b, #ff416c);
    padding: 10px 20px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    text-align: center;
    margin: 20px auto;
    width: max-content;
}
</style>

<div class="stylish-text">WHERE</div>

In [24]:
q = """

SELECT * FROM jugadores

WHERE country_of_birth = 'Brazil'
AND
market_value_in_eur >= 10000

"""
df_ejercicio = pysqldf(q)

In [25]:
df_ejercicio

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,77,None,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,None,NaN,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.000,24500000.000
1,109,None,Dedê,Dedê,2013,825,dede,Brazil,Belo Horizonte,Brazil,...,None,NaN,None,Football Concept,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dede/profil/sp...,TR1,Eskisehirspor,400000.000,9500000.000
2,1331,Kevin,Kuranyi,Kevin Kuranyi,2015,533,kevin-kuranyi,Brazil,Rio de Janeiro,Germany,...,None,NaN,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/kevin-kuranyi/...,L1,TSG 1899 Hoffenheim Fußball-Spielbetriebs GmbH,1250000.000,12000000.000
3,1426,None,Cacau,Cacau,2013,79,cacau,Brazil,Santo André,Germany,...,right,179.000,None,NESS & Network,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/cacau/profil/s...,L1,Verein für Bewegungsspiele Stuttgart 1893,350000.000,8000000.000
4,1613,None,Vivian,Vivian,2013,855,vivian,Brazil,Caçapava do Sul,Brazil,...,None,NaN,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/vivian/profil/...,FR1,EA Guingamp,100000.000,1500000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,1082823,None,Newerton,Newerton,2023,660,newerton,Brazil,Palmares,Brazil,...,right,165.000,2028-06-30 00:00:00,Bertolucci Sports,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/newerton/profi...,UKR1,FC Shakhtar Donetsk,2500000.000,3000000.000
1489,1082850,None,Deivid Washington,Deivid Washington,2023,631,deivid-washington,Brazil,Itumbiara,Brazil,...,right,187.000,2030-06-30 00:00:00,Bertolucci Sports,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/deivid-washing...,GB1,Chelsea Football Club,9000000.000,9000000.000
1490,1083965,None,Juan Alvina,Juan Alvina,2023,18303,juan-alvina,Brazil,Rio de Janeiro,Brazil,...,left,165.000,2026-06-30 00:00:00,OTB Sports,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/juan-alvina/pr...,UKR1,FK Oleksandriya,200000.000,200000.000
1491,1086381,None,Erick,Erick,2023,520,erick,Brazil,São Paulo,Brazil,...,right,176.000,2024-06-30 00:00:00,TINMO,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/erick/profil/s...,BE1,Cercle Brugge Koninklijke Sportvereniging,100000.000,100000.000
1492,1100480,Thiago,Dombroski,Thiago Dombroski,2023,7378,thiago-dombroski,Brazil,Curitiba,Poland,...,left,190.000,2025-06-30 00:00:00,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/thiago-dombros...,PO1,Portimonense Futebol SAD,350000.000,400000.000

In [26]:
q = """

SELECT first_name, country_of_birth, market_value_in_eur,last_season FROM jugadores

WHERE country_of_birth = 'Brazil'
AND
market_value_in_eur >= 10000

"""
df_ejercicio = pysqldf(q)

In [27]:
df_ejercicio

     first_name country_of_birth  market_value_in_eur  last_season
0          None           Brazil           200000.000         2012
1          None           Brazil           400000.000         2013
2         Kevin           Brazil          1250000.000         2015
3          None           Brazil           350000.000         2013
4          None           Brazil           100000.000         2013
...         ...              ...                  ...          ...
1488       None           Brazil          2500000.000         2023
1489       None           Brazil          9000000.000         2023
1490       None           Brazil           200000.000         2023
1491       None           Brazil           100000.000         2023
1492     Thiago           Brazil           350000.000         2023

[1493 rows x 4 columns]

<style>
.stylish-text {
    font-family: Arial, sans-serif;
    font-size: 16px;
    font-weight: bold;
    color: #ffffff;
    background: linear-gradient(135deg, #ff4b2b, #ff416c);
    padding: 10px 20px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    text-align: center;
    margin: 20px auto;
    width: max-content;
}
</style>

<div class="stylish-text">GROUP BY</div>

CREAR UNA TABLA QUE NOS MUESTRE EL TOP 10 DE VALOR PROMEDIO DE MERCADO DE JUGADORES AGRUPANDO POR CLUB ACTUAL Y ORDENADO DE MAYO A MENOR PROMEDIO

In [28]:
#Configurar pandas para mostrar numeros en formato completo
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [36]:
q= """

SELECT
current_club_name as nombre_del_club,

avg(highest_market_value_in_eur) as promedio_valor

FROM jugadores

GROUP BY 1 

ORDER BY promedio_valor DESC

LIMIT 11

"""

top_10_clubes = pysqldf(q)

In [33]:
top_10_clubes

                      nombre_del_club  promedio_valor
0          Real Madrid Club de Fútbol    42483333.333
1               Futbol Club Barcelona    34808196.721
2       Manchester City Football Club    34635000.000
3   Paris Saint-Germain Football Club    33676984.127
4     Manchester United Football Club    27897348.485
5               Chelsea Football Club    25879375.000
6             Liverpool Football Club    25631439.394
7                   FC Bayern München    24894485.294
8               Arsenal Football Club    21899305.556
9     Tottenham Hotspur Football Club    21736507.937
10     Club Atlético de Madrid S.A.D.    18484770.115

<style>
.stylish-text {
    font-family: Arial, sans-serif;
    font-size: 16px;
    font-weight: bold;
    color: #ffffff;
    background: linear-gradient(135deg, #ff4b2b, #ff416c);
    padding: 10px 20px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    text-align: center;
    margin: 20px auto;
    width: max-content;
}
</style>

<div class="stylish-text">HAVING</div>

APLICAMOS UN HAVING PARA QUE TOME SOLO LOS VALORES DEL PROMEDIO_VALOR <1500000

SE APLICA HAVING PORQUE LA CONDICION LA ESTAMOS APLICANDO SOBRE EL VALOR FILTRADO EN EL GROUPBY. SI NO HUBIESE NINGUN VALOR FILTRADO UTILIZARIAMOS LA COMANDA WJERE

In [37]:
q= """

SELECT
current_club_name as nombre_del_club,

avg(highest_market_value_in_eur) as promedio_valor

FROM jugadores

GROUP BY 1 

HAVING promedio_valor < 15000000

ORDER BY promedio_valor DESC

LIMIT 11

"""

top_10_clubes = pysqldf(q)

In [39]:
top_10_clubes

                                 nombre_del_club  promedio_valor
0                         RasenBallsport Leipzig    14572058.824
1                Nottingham Forest Football Club    14559693.878
2                         Sport Lisboa e Benfica    14407258.065
3                      Aston Villa Football Club    14250526.316
4                    Bayer 04 Leverkusen Fußball    14141086.957
5                          Everton Football Club    14011805.556
6                      Associazione Calcio Milan    13161011.905
7     Football Club Internazionale Milano S.p.A.    12846171.171
8                 Real Sociedad de Fútbol S.A.D.    12742028.986
9                           Fulham Football Club    12564015.152
10  Association sportive de Monaco Football Club    12000000.000

<style>
.stylish-text {
    font-family: Arial, sans-serif;
    font-size: 16px;
    font-weight: bold;
    color: #ffffff;
    background: linear-gradient(135deg, #ff4b2b, #ff416c);
    padding: 10px 20px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    text-align: center;
    margin: 20px auto;
    width: max-content;
}
</style>

<div class="stylish-text">LEFT JOIN</div>

SUPONGAMOS QUE PARTIMOS DE LA TABLA DE DE LOS TOP 10 SEGUN VALUACION PROMEDIO DE JUGADORES

In [40]:
top_10_clubes

                                 nombre_del_club  promedio_valor
0                         RasenBallsport Leipzig    14572058.824
1                Nottingham Forest Football Club    14559693.878
2                         Sport Lisboa e Benfica    14407258.065
3                      Aston Villa Football Club    14250526.316
4                    Bayer 04 Leverkusen Fußball    14141086.957
5                          Everton Football Club    14011805.556
6                      Associazione Calcio Milan    13161011.905
7     Football Club Internazionale Milano S.p.A.    12846171.171
8                 Real Sociedad de Fútbol S.A.D.    12742028.986
9                           Fulham Football Club    12564015.152
10  Association sportive de Monaco Football Club    12000000.000

AHORA LO QUE QUEREMOS SABER ES COMO SE LLAMA CADA UNO DE LOS ESTADIOS DE ESTOS CLUBES, PARA ESO UNIMOS ESTA TABLA CON LA TABLA CLUBES

In [46]:
clubes

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,31,26.800,11,35.500,1,Merck-Stadion am Böllenfalltor,17810,€-1.48m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,NaN,27,28.200,15,55.600,6,Yekaterinburg Arena,23000,€-895k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,39,26.000,17,43.600,14,Tüpraş Stadyumu,42445,€-26.00m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,26,27.100,18,69.200,16,Olimpico di Roma,73261,+€63.20m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,30,25.500,22,73.300,21,Tottenham Hotspur Stadium,62850,€-151.40m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,68608,cf-os-belenenses,CF Os Belenenses,PO1,NaN,30,25.700,5,16.700,0,Estádio do Restelo,19980,+-0,NaN,2017,../data/raw/transfermarkt-scraper/2017/clubs.j...,https://www.transfermarkt.co.uk/cf-os-belenens...
422,724,fc-volendam,Football Club Volendam,NL1,NaN,32,22.300,17,53.100,3,Kras Stadion,7384,+€2.30m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/fc-volendam/st...
423,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,NaN,25,26.800,17,68.000,17,Gewiss Stadium,21747,+€74.49m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/atalanta-berga...
424,979,moreirense-fc,Moreirense Futebol Clube,PO1,NaN,29,25.800,17,58.600,3,Estádio C. J. de Almeida Freitas,6153,€-2.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/moreirense-fc/...
425,984,west-bromwich-albion,West Bromwich Albion,GB1,NaN,25,27.800,8,32.000,4,The Hawthorns,26850,€-1.35m,NaN,2020,../data/raw/transfermarkt-scraper/2020/clubs.j...,https://www.transfermarkt.co.uk/west-bromwich-...

ON a.nombre_del_club = b.name   es la key que aparece en las 2 columnas

In [49]:
q = """ 
SELECT a.*,

 b.stadium_name

FROM top_10_clubes a 

LEFT JOIN  clubes b 

ON a.nombre_del_club = b.name

"""

pysqldf(q)

,nombre_del_club,promedio_valor,stadium_name
0,RasenBallsport Leipzig,14572058.824,Red Bull Arena
1,Nottingham Forest Football Club,14559693.878,The City Ground
2,Sport Lisboa e Benfica,14407258.065,Estádio da Luz
3,Aston Villa Football Club,14250526.316,Villa Park
4,Bayer 04 Leverkusen Fußball,14141086.957,BayArena
5,Everton Football Club,14011805.556,Goodison Park
6,Associazione Calcio Milan,13161011.905,Giuseppe Meazza
7,Football Club Internazionale Milano S.p.A.,12846171.171,Giuseppe Meazza
8,Real Sociedad de Fútbol S.A.D.,12742028.986,Reale Arena
9,Fulham Football Club,12564015.152,Craven Cottage
10,Association sportive de Monaco Football Club,12000000.000,Stade Louis-II

![JOINS](https://i.sstatic.net/4zjxm.png)